In [43]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.io as pio

# Force plotly to open in a web browser, bypassing Jupyter/Notebook rendering errors
pio.renderers.default = 'browser'

In [2]:
df = pd.read_csv('/Users/swanithambadas/Documents/ai-ml/Project/Dataset/fraudTrain.csv')

In [3]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [4]:
df.columns.tolist()

['Unnamed: 0',
 'trans_date_trans_time',
 'cc_num',
 'merchant',
 'category',
 'amt',
 'first',
 'last',
 'gender',
 'street',
 'city',
 'state',
 'zip',
 'lat',
 'long',
 'city_pop',
 'job',
 'dob',
 'trans_num',
 'unix_time',
 'merch_lat',
 'merch_long',
 'is_fraud']

In [5]:
df.dtypes

Unnamed: 0                 int64
trans_date_trans_time     object
cc_num                     int64
merchant                  object
category                  object
amt                      float64
first                     object
last                      object
gender                    object
street                    object
city                      object
state                     object
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                       object
dob                       object
trans_num                 object
unix_time                  int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

In [6]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

### As the data is very clean at this point, we add noise to mimic the actual transactional data 
### Later clean it and save the cleaned for further visualizations.

In [7]:
#filling null values in category column, by random sampling based on index
cat_nulls = df.sample(frac=0.02, random_state=42).index

In [8]:
# filling null values in merchant column
merch_nulls = df.sample(frac=0.01, random_state=99).index

In [9]:
df.loc[cat_nulls, 'category'] = np.nan
df.loc[merch_nulls, 'merchant'] = np.nan

In [10]:
# this applies a lambda function to the city column by adding unwanted spaces to the city names.
df['city'] = df['city'].apply(lambda x: f"   {x}  " if isinstance(x, str) else x)

In [11]:
# selecting the indices where we will changing the amount to negative values.
neg_amt_idx = df.sample(frac=0.005, random_state=11).index

In [12]:
df.loc[neg_amt_idx, 'amt'] = -df.loc[neg_amt_idx, 'amt']

In [13]:
duplicates = df.sample(n=100, random_state=7)
df = pd.concat([df, duplicates], ignore_index=True)

In [14]:
df.isnull().sum()

Unnamed: 0                   0
trans_date_trans_time        0
cc_num                       0
merchant                 12968
category                 25936
amt                          0
first                        0
last                         0
gender                       0
street                       0
city                         0
state                        0
zip                          0
lat                          0
long                         0
city_pop                     0
job                          0
dob                          0
trans_num                    0
unix_time                    0
merch_lat                    0
merch_long                   0
is_fraud                     0
dtype: int64

In [15]:
(df['amt'] < 0).sum()

np.int64(6484)

In [16]:
df.duplicated().sum()

np.int64(100)

In [17]:
df.shape

(1296775, 23)

In [18]:
df.isnull().sum()[df.isnull().sum() > 0]

merchant    12968
category    25936
dtype: int64

# Cleaning of data

In [19]:
# cleaning the dirty city strings
df['city'] = df['city'].str.strip()

In [20]:
# making the amount string as an absolute value
df['amt'] = df['amt'].abs()

In [21]:
df = df.drop_duplicates()

In [22]:
df['category'] = df['category'].fillna("UNKNOWN_CATEGORY")
df['merchant'] = df['merchant'].fillna("UNKNOWN_MERCHANT")

In [23]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [24]:
df.columns.tolist()

['Unnamed: 0',
 'trans_date_trans_time',
 'cc_num',
 'merchant',
 'category',
 'amt',
 'first',
 'last',
 'gender',
 'street',
 'city',
 'state',
 'zip',
 'lat',
 'long',
 'city_pop',
 'job',
 'dob',
 'trans_num',
 'unix_time',
 'merch_lat',
 'merch_long',
 'is_fraud']

In [25]:
df['population']=df['city_pop']

In [26]:
df.drop(columns=['city_pop'], inplace=True)

In [27]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,population
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,3495
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,149
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,4154
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,1939
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,99

### Data preparation for model training

In [28]:
# converting the datetime format into actual date and and actual hours format
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])
df['hour'] = df['trans_date_trans_time'].dt.hour
df['day_of_week'] = df['trans_date_trans_time'].dt.dayofweek

In [29]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,population,hour,day_of_week
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,3495,0,1
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,149,0,1
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,4154,0,1
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,1939,0,1
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,99,0,1

In [30]:
df['hour'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)

In [31]:
df['day_of_week'].unique()

array([1, 2, 3, 4, 5, 6, 0], dtype=int32)

In [32]:
# 2. Calculate User Age from DOB
# XGBoost can't read a '1985-10-25' string. It needs a number (e.g., 38).
df['dob'] = pd.to_datetime(df['dob'])
# Using 2026 as the current year based on your system context
df['age'] = 2026 - df['dob'].dt.year

In [33]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,population,hour,day_of_week,age
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,3495,0,1,38
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,149,0,1,48
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,4154,0,1,64
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,1939,0,1,59
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,99,0,1,40

In [34]:
print("Calculating User-to-Merchant distances...")
def haversine_vectorized(lat1, lon1, lat2, lon2):
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2
    return 6371 * 2 * np.arcsin(np.sqrt(a))
    
df['dist_to_merchant_km'] = haversine_vectorized(
        df['lat'], df['long'], df['merch_lat'], df['merch_long']
    )

Calculating User-to-Merchant distances...

In [35]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,trans_num,unix_time,merch_lat,merch_long,is_fraud,population,hour,day_of_week,age,dist_to_merchant_km
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,3495,0,1,38,78.597568
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,149,0,1,48,30.212176
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,4154,0,1,64,108.206083
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,1939,0,1,59,95.673231
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,99,0,1,40,77.556744

In [36]:
df['dist_to_merchant_km'].max()

np.float64(152.11717310595034)

In [37]:
df['dist_to_merchant_km'].mean()

np.float64(76.11465060395156)

In [38]:
df['dist_to_merchant_km'].describe()

count    1.296675e+06
mean     7.611465e+01
std      2.911693e+01
min      2.225452e-02
25%      5.533491e+01
50%      7.823175e+01
75%      9.850327e+01
max      1.521172e+02
Name: dist_to_merchant_km, dtype: float64

In [52]:
# Target Encode 'category'
cat_target_means = df.groupby('category')['is_fraud'].mean()
df['category_encoded'] = df['category'].map(cat_target_means)
    
    # Target Encode 'gender'
gender_target_means = df.groupby('gender')['is_fraud'].mean()
df['gender_encoded'] = df['gender'].map(gender_target_means)

In [53]:
avg_dist_legit = df[df['is_fraud'] == 0]['dist_to_merchant_km'].mean()
avg_dist_fraud = df[df['is_fraud'] == 1]['dist_to_merchant_km'].mean()
print(f"Distance Signal: Legitimate avg = {avg_dist_legit:.2f}km | Fraud avg = {avg_dist_fraud:.2f}km")

Distance Signal: Legitimate avg = 76.11km | Fraud avg = 76.27km

In [54]:
# Insight B: Highest Risk Categories (Percentage of transactions that are fraud)
fraud_rate_by_cat = df.groupby('category')['is_fraud'].mean().sort_values(ascending=False) * 100
print(f"\nTop 3 Riskiest Categories (Highest % of fraud):")
print(fraud_rate_by_cat.head(3).to_string())

Top 3 Riskiest Categories (Highest % of fraud):
category
shopping_net    1.763617
misc_net        1.450700
grocery_pos     1.405255

In [48]:
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
correlations = df[numeric_cols].corr()['is_fraud'].sort_values(ascending=False)
print("\nFeature Correlation to Fraud (Closer to 1 or -1 is a stronger signal):")
print(correlations.drop('is_fraud').to_string())

Feature Correlation to Fraud (Closer to 1 or -1 is a stronger signal):
amt                    0.219404
hour                   0.013799
age                    0.012378
population             0.002136
lat                    0.001894
merch_lat              0.001741
day_of_week            0.001739
merch_long             0.001721
long                   0.001721
dist_to_merchant_km    0.000403
cc_num                -0.000981
zip                   -0.002162
Unnamed: 0            -0.004767
unix_time             -0.005078

In [44]:
fraud_counts = df['is_fraud'].value_counts().reset_index()
fraud_counts.columns = ['is_fraud', 'count']
fraud_counts['is_fraud'] = fraud_counts['is_fraud'].map({0: 'Legitimate', 1: 'Fraud'})
    
fig1 = px.pie(fraud_counts, names='is_fraud', values='count', 
                  title="1. Class Imbalance (Legitimate vs Fraud)",
                  color='is_fraud', color_discrete_map={'Legitimate':'blue', 'Fraud':'red'})
fig1.show()

In [45]:
fig2 = px.box(df, x='is_fraud', y='amt', color='is_fraud',
                  title="2. Transaction Amount Distribution (Log Scale)",
                  labels={'is_fraud': 'Is Fraud?', 'amt': 'Transaction Amount ($)'},
                  log_y=True, color_discrete_map={0:'blue', 1:'red'})
    # Update x-axis labels for clarity
fig2.update_xaxes(tickvals=[0, 1], ticktext=['Legitimate', 'Fraud'])
fig2.show()

In [46]:
fraud_only = df[df['is_fraud'] == 1]
category_counts = fraud_only['category'].value_counts().reset_index()
category_counts.columns = ['category', 'fraud_count']
    
fig3 = px.bar(category_counts, x='category', y='fraud_count',
                  title="3. Fraudulent Transactions by Merchant Category",
                  labels={'category': 'Merchant Category', 'fraud_count': 'Number of Fraud Events'},
                  color='fraud_count', color_continuous_scale='Reds')
fig3.update_layout(xaxis_tickangle=-45)
fig3.show()

In [49]:
hourly_fraud = fraud_only.groupby('hour').size().reset_index(name='fraud_count')
fig4 = px.line(hourly_fraud, x='hour', y='fraud_count', markers=True,
                   title="4. Fraudulent Transactions by Time of Day (Hour)",
                   labels={'hour': 'Hour of Day (0-23)', 'fraud_count': 'Number of Fraud Events'},
                   line_shape='spline')
fig4.show()